Fixed the UI issue and added dialogs to actions
arpitghura/NotesJar pull request #12
Opened 2023-12-09 07:44 UTC by Sami3160

The constant appearance no-notes.gif by delete note is removed. It was caused by some notes.length field, but it is fixed.
Also to replace that gif i added a simple modal that appears on various actions like add/update/delete.
The modal can automatically disappears after 1500ms and some by 1000ms. or can by explicitly disappeared by clicking on any where on window.
After adding new note, it shows...
![Screenshot (76)](https://github.com/arpitghura/NotesJar/assets/110652247/74b15c04-3087-44d5-8a25-22a9b4e483c3)
after updating any note it shows....
![Screenshot (77)](https://github.com/arpitghura/NotesJar/assets/110652247/f8a05616-fc91-44b5-be6b-d5f98d5f5952)
and finally after deleting any note...
![Screenshot (78)](https://github.com/arpitghura/NotesJar/assets/110652247/c5cf937c-f82e-4aa6-9a80-694450749553)
Basically i just removed the bug or replaced bug with some modals, i hope you like it😊
please do accept my pull request😄

2023-12-10 20:41 UTC, arpitghura commented
Hey @Sami3160 You have done a great job, but this will not create a good user experience. 

Instead, you can show a toast message in the top right/center.

2023-12-11 05:43 UTC, Sami3160 commented
> Hey @Sami3160 You have done a great job, but this will not create a good user experience.
> 
> Instead, you can show a toast message in the top right/center.

changes are done in this pr, check the updated preview:
![Screenshot (97)](https://github.com/arpitghura/NotesJar/assets/110652247/da429b20-4ade-4da2-8a0f-f19ae1c0d150)
![Screenshot (99)](https://github.com/arpitghura/NotesJar/assets/110652247/52605d03-36b1-49e7-9e8c-c228422cec4b)
![Screenshot (98)](https://github.com/arpitghura/NotesJar/assets/110652247/920b978f-9c0a-4f61-a969-13adc15ffd55)

2023-12-15 17:06 UTC, arpitghura requested changes
Kindly review these reviews.

2023-12-15 17:06 UTC, arpitghura commented on main.js
> +    x.innerHTML=msg;
use `innerText` instead of `innerHTML`

2023-12-15 17:06 UTC, arpitghura commented on main.js
> +        }
There is no need to check for the count as you are already inside the function call of the delete function.

2023-12-15 17:06 UTC, arpitghura commented on main.js
> +
1. Return `notes` from the function and reuse this function inside `updateLSData` to fetch all notes.
2. change the function name to something like `getAllNotes`
3. Use the `notes.length` property while fetching the length of the notes or create a separate function to return the length by passing `notes` as the parameter.

2023-12-17 06:48 UTC, Sami3160 commented on main.js
> +    x.innerHTML=msg;
okay sir, check new pr, all changes are done as you told me

2023-12-17 08:35 UTC, arpitghura approved these changes
Good Work, Sami

2023-12-17 08:36 UTC, merged