added contribution.md file
arpitghura/NotesJar pull request #7
Opened 2023-12-07 11:50 UTC by Devesh-Daku

Added contribution.md files #5

2023-12-07 12:36 UTC, arpitghura requested changes
Make these required changes.

2023-12-07 12:36 UTC, arpitghura commented on CONTRIBUTION.md
> +    git clone https://github.com/your-username/[project-name].git
```suggestion
    git clone https://github.com/<your-username>/NotesJar.git 
```
Adding project name and also add a line to change `<your-username>` with their own username.

2023-12-07 12:36 UTC, arpitghura commented on CONTRIBUTION.md
> +    git commit -m "Your clear and concise message"
Add this blog link on `How to write Better Git Commit Messages` by `FreeCodeCamp` along with the credits.

Link to the post: [https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/)

2023-12-07 12:36 UTC, arpitghura commented on CONTRIBUTION.md
> +6. Open a pull request, referencing any relevant issues.
Remove the word `any`.

Mention these:

The PR should contain about:
- the problem or issue tag
- the solution approach you have made
- any big file changes
- any bug/issue that can arise from the changes.

2023-12-07 12:36 UTC, arpitghura commented on CONTRIBUTION.md
> +Thank you for contributing to [Project Name]! 🚀
Change the [Project Name] to NotesJar. 
and [Project Licence] to MIT.

2023-12-08 09:01 UTC, deveshio commented
I have update the contribution.md file

2023-12-08 16:25 UTC, arpitghura approved these changes
Looks Good to Me.

2023-12-08 16:28 UTC, arpitghura commented
One thing to change is the name of the file, the file name should be `CONTRIBUTING.md`

2023-12-09 04:06 UTC, Devesh-Daku commented
Sir ,I request you please check your requirements and merge  this update with your branch .
i have update the name

2023-12-10 21:13 UTC, arpitghura approved these changes
LGTM

2023-12-10 21:13 UTC, merged